### ISSUE TITLE
Poe token creation error

### ISSUE THREAD

**Issue by dolodi** [xtekky/openai-gpt4#31]
traceback:
'token'
email False
send_code {'data': {'sendVerificationCode': {'status': 'invalid_email', 'errorMessage': 'The email you entered is not valid. Please try again.'}}, 'extensions': {'is_final': True}}
Traceback (most recent call last):
  File "c:\Users\MSI-PC\OneDrive\Desktop\openai-gpt4-main\poe_test.py", line 4, in <module>
    token = quora.Account.create(proxy = None,logging = True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\MSI-PC\OneDrive\Desktop\openai-gpt4-main\quora\__init__.py", line 218, in create
    if len(messages["messages"]) > 0:
           ~~~~~~~~^^^^^^^^^^^^
KeyError: 'messages'

**Comment by xtekky** [comment]
fixed, if this error persists, consider using proxies
